# Generated by Django 5.2.7 on 2025-10-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AxisBankRemitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('lei_code', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField()),
                ('cheque_number', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=15)),
                ('other_number', models.CharField(blank=True, max_length=15, null=True)),
                ('branch', models.CharField(max_length=255)),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RemitterAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('remitter_account_number', models.CharField(max_length=50)),
                ('remitter_name', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('remitter_LEI_code', models.CharField(blank=True, max_length=255, null=True)),
                ('remitter_address', models.TextField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('other_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('unique_code', models.CharField(editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnionBankRemitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=30, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
