# Generated by Django 5.2.7 on 2025-10-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_filler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remitteraccount',
            name='unique_code',
            field=models.CharField(max_length=6),
        ),
    ]
