# Generated by Django 5.2.7 on 2025-10-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_filler', '0002_alter_remitteraccount_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='unique_code',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
