# Generated by Django 5.2.7 on 2025-10-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_filler', '0003_alter_signup_unique_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxisBankBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_address', models.TextField(blank=True, null=True)),
                ('lei_code', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(max_length=20)),
            ],
        ),
    ]
