# Generated by Django 5.2.7 on 2025-10-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_filler', '0005_alter_signup_phone_alter_signup_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
