# Generated by Django 5.2.7 on 2025-10-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_filler', '0006_alter_signup_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remitteraccount',
            name='remitter_LEI_code',
        ),
        migrations.AddField(
            model_name='remitteraccount',
            name='ifsc_code',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
