# Generated by Django 5.2.7 on 2025-10-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_filler', '0007_remove_remitteraccount_remitter_lei_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='axisbankremitter',
            name='lei_code',
        ),
        migrations.AddField(
            model_name='axisbankremitter',
            name='ifsc_code',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
