# Generated by Django 5.2.7 on 2025-10-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_filler', '0008_remove_axisbankremitter_lei_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='axisbankbeneficiary',
            name='transaction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
