# Generated by Django 5.2.7 on 2025-10-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_filler', '0009_axisbankbeneficiary_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='unionbankremitter',
            name='other_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
