# Generated by Django 5.2.7 on 2025-10-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_filler', '0010_unionbankremitter_other_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='axisbankbeneficiary',
            name='unique_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
