# Generated by Django 5.2.7 on 2025-10-31 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_filler', '0011_axisbankbeneficiary_unique_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='axisbankbeneficiary',
            name='lei_code',
        ),
        migrations.RemoveField(
            model_name='axisbankbeneficiary',
            name='transaction_amount',
        ),
    ]
